JobBoard/Controllers/JobController.cs
using JobBoard.Handlers;
using JobBoard.Logic.Interfaces;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;

namespace JobBoard.Controllers
{
    public class JobController : BaseController
    {
        readonly IJob _job;
        RegionReader _regionReader = new RegionReader();
        readonly IHttpContextAccessor _httpContext;

        public JobController(IJob job , IHttpContextAccessor httpContext) : base(httpContext)
        {
            _job = job;
            _httpContext = httpContext;
        }

        [Route("job-list")]
        public IActionResult Index()
        {
            return View();
        }

        [Route("job")]
        public IActionResult Create()
        {
            return View();
        }

        //[HttpPost]
        //public IActionResult CreatOrEditJob()
        //{
        //    try
        //    {
        //        if (ModelState.IsValid)
        //        {

        //        }
        //    }
        //    catch (Exception ex)
        //    {
        //        throw ex;
        //    }
        //}

        [Route("job/details")]
        ///[Route("job/details/{title}")]
        public IActionResult Details(int jobId)
        {
            return View();
        }
        
        //[Route("recruiter/jobs")]
        //[Authorize]
        //public IActionResult RecruiterJobs()
        //{
        //    try
        //    {

        //    }
        //    catch (Exception)
        //    {

        //        throw;
        //    }
        //}


    }
}

JobBoard/Controllers/UserController.cs
using AutoMapper;
using JobBoard.DTO.EdiModel;
using JobBoard.Enum;
using JobBoard.Logic.Interfaces;
using JobBoard.ViewModels;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace JobBoard.Controllers
{
    public class UserController : BaseController
    {
        readonly IHttpContextAccessor _httpContext;
        readonly IUser _user;
        readonly IMapper _mapper;

        public UserController(IHttpContextAccessor httpContext, IUser user, IMapper mapper) : base(httpContext)
        {
            _httpContext = httpContext;
            _user = user;
            _mapper = mapper;
        }

        public ActionResult Index()
        {
            var data = GetUserById(UserId);
            return View(data);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit( UserModel model)
        {
            try
            {
                if (!ModelState.IsValid)
                {
                    TempData["Error"] = "Please Input the Required Information(s)";
                    return View("Index", model);
                }
                var resp = _mapper.Map<UserEM>(model);
                var response = _user.Edit(resp);
                if (response == RequestStatus.Success)
                {
                    TempData["Success"] = "Updated Successfully";
                    return View("Index", model);
                }
                
                if (response == RequestStatus.NoEntryFound)
                {
                    TempData["Error"] = "No Record Found For this user";
                    return View("Index", model);
                }

                return View("Index", model);
            }
            catch
            {
                return View("Index");
            }
        }

        public UserModel GetUserById(int Id)
        {
            var data = _user.GetById(Id);
            var response = _mapper.Map<UserModel>(data);
            return response;
        }

    }
}

JobBoard/Views/Shared/TopBar.cshtml
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@

@*@{
    var Email = @HttpContextAccessor.HttpContext.Session.GetString("Email");
    var AffiliateNumber = @HttpContextAccessor.HttpContext.Session.GetString("AffiliateNumber");
    var userId = @HttpContextAccessor.HttpContext.Session.GetString("UserId");
    var Role = @HttpContextAccessor.HttpContext.Session.GetString("Role");

}*@

<!-- Topbar -->
<nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

    <!-- Sidebar Toggle (Topbar) -->
    <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
        <i class="fa fa-bars"></i>
    </button>

    <!-- Topbar Search -->
    <form class="d-none d-sm-inline-block form-inline mr-auto ml-md-3 my-2 my-md-0 mw-100 navbar-search">
        <div class="input-group">
            <input type="text" class="form-control bg-light border-0 small" placeholder="Search for..." aria-label="Search" aria-describedby="basic-addon2">
            <div class="input-group-append">
                <button class="btn btn-facebook top_search_bar__" type="button">
                    <i class="fas fa-search fa-sm"></i>
                </button>
            </div>
        </div>
    </form>

    <!-- Topbar Navbar -->
    <ul class="navbar-nav ml-auto">

        <!-- Nav Item - Search Dropdown (Visible Only XS) -->
        <li class="nav-item dropdown no-arrow d-sm-none">
            <a class="nav-link dropdown-toggle" href="#" id="searchDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <i class="fas fa-search fa-fw"></i>
            </a>
            <!-- Dropdown - Messages -->
            <div class="dropdown-menu dropdown-menu-right p-3 shadow animated--grow-in" aria-labelledby="searchDropdown">
                <form class="form-inline mr-auto w-100 navbar-search">
                    <div class="input-group">
                        <input type="text" class="form-control bg-light border-0 small" placeholder="Search for..." aria-label="Search" aria-describedby="basic-addon2">
                        <div class="input-group-append">
                            <button class="btn btn-primary" type="button">
                                <i class="fas fa-search fa-sm"></i>
                            </button>
                        </div>
                    </div>
                </form>
            </div>
        </li>

        <!-- Nav Item - Messages -->
        <li class="nav-item ">
            <a class="nav-link  text-black-50 text-lg toplink__">
                uiwefceivnuiodcsni
            </a>

            <!-- Counter - Messages -->
        </li>


        <!-- Nav Item - Alerts -->
        <li class="nav-item dropdown no-arrow mx-4">
            <a class="nav-link dropdown-toggle" href="#" id="alertsDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <i class="fas fa-bell fa-fw" id="notificationBell"></i>
                <!-- Counter - Alerts -->
                <span class="badge badge-danger badge-counter" id="notificationCount"></span>
            </a>
            <!-- Dropdown - Alerts -->
            <div class="dropdown-list dropdown-menu dropdown-menu-right shadow animated--grow-in" aria-labelledby="alertsDropdown" style="width:25rem">
                <h6 class="dropdown-header">
                    Alerts Center
                </h6>
                <ul id="no__styling">
                 
                </ul>
                <a class="dropdown-item text-center small text-gray-500" href="/Notification/Index" data->Show All Alerts</a>
            </div>
        </li>

        <div class="topbar-divider d-none d-sm-block"></div>

        <!-- Nav Item - User Information -->
        <li class="nav-item dropdown no-arrow">
            <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <span class="mr-2 d-none d-lg-inline text-gray-600 small">Profile </span>
                <i class="fas fa-user-circle text-primary" style="font-size: xx-large;"></i>
                @*<img class="img-profile rounded-circle fa fa-user-circle-o">*@

            </a>
            <!-- Dropdown - User Information -->
            <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in" aria-labelledby="userDropdown">
                <a class="dropdown-item" asp-action="UserProfile" asp-controller="User">
                    <i class="fas fa-user fa-sm fa-fw mr-2 text-gray-400"></i>
                    Profile
                </a>
                <a class="dropdown-item" asp-action="ChangePassword" asp-controller="Account">
                    <i class="fas fa-list fa-sm fa-fw mr-2 text-gray-400"></i>
                    Change Password
                </a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" data-toggle="modal" data-target="#logoutModal">
                    <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
                    Logout
                </a>
            </div>
        </li>

    </ul>

</nav>
<!-- End of Topbar -->

<script src="~/Config.js"></script>

<script src="~/vendor/jquery/jquery.min.js"></script>

JobBoard/Views/Shared/_AccountLayout.cshtml
<!DOCTYPE html>

<html>
<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>@ViewData["Title"] JobBoard</title>
    @*<environment include="Development">*@
    <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">

    <!-- Custom styles for this template-->
    <link href="~/Admin Styles/sb-admin-2.min.css" rel="stylesheet" />
    <link href="~/Admin Styles/stepper.css" rel="stylesheet" />

    @*<link href="~/vendor/fontawesome-free/css/all.min.css" rel="stylesheet" />
    <link href="~/vendor/fontawesome-free/css/fontawesome.min.css" rel="stylesheet" />*@

    @*</environment>*@
</head>
<body class="bg-gradient-tertiary">

    <div class="container">

        @RenderBody()

    </div>

    @RenderSection("scripts", required: false)

<script src="~/Admin Styles/jquery.min.js"></script>
<script src="~/Admin Styles/bootstrap.bundle.min.js"></script>

    <!-- Core plugin JavaScript-->
    <script src="~/Admin Styles/jquery.easing.min.js"></script>

    <!-- Custom scripts for all pages-->
    <script src="~/Admin Styles/sb-admin-2.min.js"></script>
    <script src="~/Admin Styles/stepper.js"></script>

    <!-- Page level plugins -->
    <script src="~/Admin Styles/jquery.dataTables.min.js"></script>
    <script src="~/Admin Styles/dataTables.bootstrap4.min.js"></script>

    <!-- Page level custom scripts -->
    <script src="~/Admin Styles/datatables-demo.js"></script>

</body>
</html>

JobBoard/Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link href="~/Admin Styles/dataTables.bootstrap4.min.css" rel="stylesheet" />
    <link href="~/Admin Styles/sb-admin-2.min.css" rel="stylesheet" />
    <link href="~/Admin Styles/stepper.css" rel="stylesheet" />
</head>
<body id="page-top" style="margin:0;">

    <div id="loader"></div>
    <div id="wrapper">

        <partial name="_AdminSideBar" />

        <!-- Content Wrapper -->
        <div id="content-wrapper" class="d-flex flex-column">
            <!-- Main Content -->
            <div id="content">
                <partial name="TopBar" />

                @RenderBody()
            </div>
        </div>
    </div>

    <script src="~/Admin Styles/jquery.min.js"></script>
    <script src="~/Admin Styles/jquery.easing.min.js"></script>
    <script src="~/Admin Styles/jquery.dataTables.min.js"></script>
    <script src="~/Admin Styles/bootstrap.bundle.min.js"></script>
    <script src="~/Admin Styles/dataTables.bootstrap4.min.js"></script>
    <script src="~/Admin Styles/datatables-demo.js"></script>
    <script src="~/Admin Styles/sb-admin-2.min.js"></script>
    <script src="~/Admin Styles/stepper.js"></script>
</body>
</html>

JobBoard/Views/Shared/_AdminSideBar.cshtml
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@

<!-- Sidebar -->
    <ul class="navbar-nav bg-gradient-secondary sidebar sidebar-dark accordion" id="accordionSidebar">

        <!-- Sidebar - Brand -->
        <a class="sidebar-brand d-flex align-items-center justify-content-center" href="#">

            <div class="sidebar-brand-text mx-3">Affiliate Platform</div>
        </a>

        <!-- Divider -->
        <hr class="sidebar-divider my-0">

        <!-- Nav Item - Dashboard -->
        <li class="nav-item active">
            <a class="nav-link" asp-action="Index" asp-controller="Recruiter">
                <i class="fas fa-fw fa-tachometer-alt"></i>
                <span>Dashboard</span>
            </a>
        </li>

        <!-- Nav Item - Leads -->
        <li class="nav-item">
            <a class="nav-link" asp-action="AffiliateList" asp-controller="Recruiter">
                <i class="fas fa-fw fa-tachometer-alt"></i>
                <span>Affiliates</span>
            </a>
        </li>

        <li class="nav-item">
            <a class="nav-link" asp-action="AdminClients" asp-controller="Admin">
                <i class="fas fa-fw fa-tachometer-alt"></i>
                <span>Clients</span>
            </a>
        </li>

        <li class="nav-item">
            <a class="nav-link" asp-action="Index" asp-controller="Lead">
                <i class="fas fa-fw fa-table"></i>
                <span>Leads</span>
            </a>
        </li>

        <!-- Nav Item - Leads -->
        <li class="nav-item">
            <a class="nav-link" asp-action="Index" asp-controller="Sales">
                <i class="fas fa-fw fa-folder"></i>
                <span>Sales</span>
            </a>
        </li>


        <!-- Divider -->
        <hr class="sidebar-divider d-none d-md-block">

        <!-- Sidebar Toggler (Sidebar) -->
        <div class="text-center d-none d-md-inline">
            <button class="rounded-circle border-0" id="sidebarToggle"></button>
        </div>

    </ul>
<!-- End of Sidebar -->

JobBoard/Views/Shared/_Footer.cshtml
<footer class="site-footer">

    <a href="#top" class="smoothscroll scroll-top">
        <span class="icon-keyboard_arrow_up"></span>
    </a>

    <div class="container">
        <div class="row mb-5">
            <div class="col-6 col-md-3 mb-4 mb-md-0">
                <h3>Search Trending</h3>
                <ul class="list-unstyled">
                    <li><a href="#">Web Design</a></li>
                    <li><a href="#">Graphic Design</a></li>
                    <li><a href="#">Web Developers</a></li>
                    <li><a href="#">Python</a></li>
                    <li><a href="#">HTML5</a></li>
                    <li><a href="#">CSS3</a></li>
                </ul>
            </div>
            <div class="col-6 col-md-3 mb-4 mb-md-0">
                <h3>Company</h3>
                <ul class="list-unstyled">
                    <li><a href="#">About Us</a></li>
                    <li><a href="#">Career</a></li>
                    <li><a href="#">Blog</a></li>
                    <li><a href="#">Resources</a></li>
                </ul>
            </div>
            <div class="col-6 col-md-3 mb-4 mb-md-0">
                <h3>Support</h3>
                <ul class="list-unstyled">
                    <li><a href="#">Support</a></li>
                    <li><a href="#">Privacy</a></li>
                    <li><a href="#">Terms of Service</a></li>
                </ul>
            </div>
            <div class="col-6 col-md-3 mb-4 mb-md-0">
                <h3>Contact Us</h3>
                <div class="footer-social">
                    <a href="#"><span class="icon-facebook"></span></a>
                    <a href="#"><span class="icon-twitter"></span></a>
                    <a href="#"><span class="icon-instagram"></span></a>
                    <a href="#"><span class="icon-linkedin"></span></a>
                </div>
            </div>
        </div>

        <div class="row text-center">
            <div class="col-12">
                <p class="copyright">
                    <small>
                        <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                        Copyright &copy;
                        <script>document.write(new Date().getFullYear());</script> All rights reserved |JobBoard
                        <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                    </small>
                </p>
            </div>
        </div>
    </div>
</footer>

JobBoard/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - JobBoard</title>

    <link href="~/Styles/custom-bs.css" rel="stylesheet" />
    <link href="~/Styles/jquery.fancybox.min.css" rel="stylesheet" />
    <link href="~/Styles/bootstrap-select.min.css" rel="stylesheet" />
    <link href="~/Styles/icomoon/style.css" rel="stylesheet" />
    <link href="~/Styles/line-icons/style.css" rel="stylesheet" />
    <link href="~/Styles/owl.carousel.min.css" rel="stylesheet" />
    <link href="~/Styles/animate.min.css" rel="stylesheet" />
    <link href="~/Styles/quill.snow.css" rel="stylesheet" />
    <link href="~/Styles/style.css" rel="stylesheet" />
    <link href="~/toastr/toastr.css" rel="stylesheet" />
    <link href="~/toastr/toastr.min.css" rel="stylesheet" />
</head>
<body id="top">

    <div id="overlayer"></div>
    <div class="loader">
        <div class="spinner-border text-primary" role="status">
            <span class="sr-only">Loading...</span>
        </div>
    </div>

    <div class="site-wrap">
        <div class="site-mobile-menu site-navbar-target">
            <div class="site-mobile-menu-header">
                <div class="site-mobile-menu-close mt-3">
                    <span class="icon-close2 js-menu-toggle"></span>
                </div>
            </div>
            <div class="site-mobile-menu-body"></div>
        </div>

        <partial name="_NavBar" />

        @RenderBody()

        <partial name="_Footer" />
    </div>

    <script src="~/Styles/js/jquery.min.js"></script>
    <script src="~/Styles/js/bootstrap.bundle.min.js"></script>
    <script src="~/Styles/js/isotope.pkgd.min.js"></script>
    <script src="~/Styles/js/stickyfill.min.js"></script>
    <script src="~/Styles/js/jquery.fancybox.min.js"></script>
    <script src="~/Styles/js/jquery.easing.1.3.js"></script>

    <script src="~/Styles/js/jquery.waypoints.min.js"></script>
    <script src="~/Styles/js/jquery.animateNumber.min.js"></script>
    <script src="~/Styles/js/owl.carousel.min.js"></script>
    <script src="~/Styles/js/quill.min.js"></script>

    <script src="~/Styles/js/bootstrap-select.min.js"></script>

    <script src="~/Styles/js/custom.js"></script>
    <script src="~/toastr/toastr.min.js"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>

JobBoard/Views/Shared/_MiscellanousLayout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link href="~/Admin Styles/dataTables.bootstrap4.min.css" rel="stylesheet" />
    <link href="~/Admin Styles/sb-admin-2.min.css" rel="stylesheet" />
    <link href="~/Admin Styles/stepper.css" rel="stylesheet" />
</head>
<body id="page-top" style="margin:0;">

    <div id="loader"></div>
    <div id="wrapper">

        <partial name="_AdminSideBar" />

        <!-- Content Wrapper -->
        <div id="content-wrapper" class="d-flex flex-column">
            <!-- Main Content -->
            <div id="content">
                <partial name="TopBar" />

                @RenderBody()
            </div>
        </div>
    </div>

    <script src="~/Admin Styles/jquery.min.js"></script>
    <script src="~/Admin Styles/jquery.easing.min.js"></script>
    <script src="~/Admin Styles/jquery.dataTables.min.js"></script>
    <script src="~/Admin Styles/bootstrap.bundle.min.js"></script>
    <script src="~/Admin Styles/dataTables.bootstrap4.min.js"></script>
    <script src="~/Admin Styles/datatables-demo.js"></script>
    <script src="~/Admin Styles/sb-admin-2.min.js"></script>
    <script src="~/Admin Styles/stepper.js"></script>
</body>
</html>

JobBoard/Views/Shared/_NavBar.cshtml
  <!-- NAVBAR -->
@using JobBoard.Enum


@if (User.Identity.IsAuthenticated)
{
    <header class="site-navbar mt-3 fixed-top bg-dark">
        <div class="container-fluid">
            <div class="row align-items-center">
                <div class="site-logo col-6"><a asp-action="Index" asp-controller="Home">JobBoard</a></div>

                <nav class="mx-auto site-navigation">
                    <ul class="site-menu js-clone-nav d-none d-xl-block ml-0 pl-0">

                        @if (User.IsInRole(RoleEnum.JobSeeker.ToString()))
                        {
                            <li><a asp-action="Index" asp-controller="Home" class="nav-link">Home</a></li>
                            <li><a asp-action="Index" asp-controller="Home">Job Listings</a></li>
                        }

                        @if (User.IsInRole(RoleEnum.Recruiter.ToString()))
                        {
                            <li><a asp-action="Index" asp-controller="Home" class="nav-link">Job Applications</a></li>
                            <li> <a asp-controller="Job" asp-action="Create" class="nav-link"><span class="mr-2 icon-add"></span>Post a Job</a></li>
                        }

                        <li><a asp-action="About" asp-controller="Home">About</a></li>
                        <li><a asp-action="Contact" asp-controller="Home">Contact</a></li>


                        <li class="has-children d-lg-none">
                            <a><span class="mr-3 icon-user"></span>Profile</a>
                            <ul class="dropdown">
                                <li><a asp-action="RegsiterJobSeeker" asp-controller="Account">My Profile</a></li>
                                <li><a asp-action="RegsiterRecruiter" asp-controller="Account">Change Password</a></li>
                                @if (User.IsInRole(RoleEnum.JobSeeker.ToString()))
                                {
                                    <li><a asp-action="RegsiterJobSeeker" asp-controller="Account">My Applications</a></li>
                                    <li><a asp-action="RegsiterJobSeeker" asp-controller="Account">Saved Jobs</a></li>
                                }

                                @*@if (User.IsInRole(RoleEnum.Recruiter.ToString()))
                                    {
                                        <li> <a asp-controller="Job" asp-action="Create" class="btn btn-outline-white border-width-2 d-none d-lg-inline-block"><span class="mr-2 icon-add"></span>Post a Job</a></li>
                                    }*@
                                <li><a asp-action="Delete" asp-controller="Account">Delete Account</a></li>

                            </ul>
                        </li>

                        <li class="d-lg-none">
                            <form asp-action="Logout" asp-controller="Account">
                                <button type="submit" class="btn btn-outline-secondary">sign out</button>
                            </form>
                        </li>
                    </ul>
                </nav>

                <div class="right-cta-menu text-right d-flex aligin-items-center col-6">
                    <div class="ml-auto">

                        <div class="btn-group">
                            <div class="dropdown">
                                <button class="btn btn-info dropdown-toggle btn-md d-none d-lg-inline-block" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-expanded="false">
                                    <span class="mr-3 icon-user"></span>Profile
                                </button>
                                <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                                    <a class="dropdown-item" asp-action="Index" asp-controller="User">My Profile</a>
                                    <a class="dropdown-item" asp-action="Manage" asp-controller="Account">Change Password</a>
                                    @if (User.IsInRole(RoleEnum.JobSeeker.ToString()))
                                    {
                                        <a class="dropdown-item" asp-action="RegsiterRecruiter" asp-controller="Account">My Applications</a>
                                        <a class="dropdown-item" asp-action="RegsiterJobSeeker" asp-controller="Account">Saved Jobs</a>
                                    }

                                    @if (User.IsInRole(RoleEnum.Recruiter.ToString()))
                                    {
                                        <a class="dropdown-item" asp-controller="Job" asp-action="Create">Post a Job</a>
                                    }

                                    <a class="dropdown-item" asp-action="RegsiterRecruiter" asp-controller="Account">Delete Account</a>
                                    <hr class="dropdown-divider"/>
                                    <form asp-action="Logout" asp-controller="Account" >
                                        <button type="submit" class="btn btn-outline-danger dropdown-item">not you?.. sign out</button>
                                    </form>
                                </div>
                            </div>
                        </div>
                        <form asp-controller="Account" asp-action="Logout" class="d-lg-inline-block d-none">
                            <button type="submit" class="btn btn-danger border-width-2  btn-md">Sign out</button>
                        </form>


                        @*<a class="btn btn-danger border-width-2 d-none d-lg-inline-block btn-md" href="#"><span class="mr-2 icon-lock_outline"></span>sign out</a>*@

                    </div>
                    <a href="#" class="site-menu-toggle js-menu-toggle d-inline-block d-xl-none mt-lg-2 ml-3"><span class="icon-menu h3 m-0 p-0 mt-2"></span></a>
                </div>
            </div>
        </div>

    </header>
}
else
{
    <header class="site-navbar mt-3">
        <div class="container-fluid">
            <div class="row align-items-center">
                <div class="site-logo col-6"><a asp-action="Index" asp-controller="Home">JobBoard</a></div>
                <nav class="mx-auto site-navigation">
                    <ul class="site-menu js-clone-nav d-none d-xl-block ml-0 pl-0">
                        <li><a asp-action="Index" asp-controller="Home" class="nav-link">Home</a></li>
                        <li><a asp-action="About" asp-controller="Home">About</a></li>
                        <li><a asp-action="Index" asp-controller="Home">Job Listings</a></li>
                        <li><a asp-action="Contact" asp-controller="Home"> Contact </a></li>
                        <li class="has-children d-lg-none">
                            <a href="services.html"> Sign Up</a>
                            <ul class="dropdown">
                                <li><a asp-action="RegsiterJobSeeker" asp-controller="Account">Job Seeker</a></li>
                                <li>
                                    <a asp-action="RegsiterRecruiter" asp-controller="Account">
                                        Recruiter
                                    </a>
                                </li>
                            </ul>
                        </li>
                        <li class="d-lg-none">
                            <a asp-action="Authentication" asp-controller="Account">Log In</a>
                        </li>
                    </ul>
                </nav>
                <div class="right-cta-menu text-right d-flex aligin-items-center col-6">
                    <div class="ml-auto">

                        <div class="btn-group">
                            <div class="dropdown">
                                <button class="btn btn-info dropdown-toggle btn-md d-none d-lg-inline-block" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-expanded="false">
                                    Sign Up
                                </button>
                                <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                                    <a class="dropdown-item" asp-action="RegsiterJobSeeker" asp-controller="Account">Job Seeker</a>
                                    <a class="dropdown-item" asp-action="RegsiterRecruiter" asp-controller="Account">Recruiter</a>
                                </div>
                            </div>
                        </div>

                        @*<a href="post-job.html" class="btn btn-outline-white border-width-2 d-none d-lg-inline-block"><span class="mr-2 icon-add"></span>Post a Job</a>*@
                        <a class="btn btn-primary border-width-2 d-none d-lg-inline-block btn-md" asp-action="Authentication" asp-controller="Account"><span class="mr-2 icon-lock_outline"></span>Log In</a>

                    </div>
                    <a href="#" class="site-menu-toggle js-menu-toggle d-inline-block d-xl-none mt-lg-2 ml-3"><span class="icon-menu h3 m-0 p-0 mt-2"></span></a>
                </div>
            </div>
        </div>

    </header>
}

JobBoard/Views/Shared/_Notification.cshtml
@if (TempData["Success"] != null)
{
    <div class="alert alert-success text-center" role="alert">
        <strong>@TempData["Success"]</strong>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
}

@if (TempData["Error"] != null)
{
    <div class="alert alert-danger text-center" role="alert">
        <strong>Message: @TempData["Error"]</strong>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
}

@if (ViewBag.Message != null)
{
    <div class="alert alert-secondary text-center" role="alert">
        <strong>@ViewBag.Message</strong>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
}